###############################################################
#
# Config File for INVISIBLE UNIVERSITY flavour of VITALITY bootstrap theme
#
#--------------------------------------------------------------
Baseurl = "https://lafisrap.github.io/job-profile/"
LanguageCode = "de-DE"
Title = "Lebenslauf und Profil - Michael Schmidt"
Theme = "hugo-university-theme"
publishDir = "docs/de"
disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
	locale = "de-DE"
	otherLocales = [
		"English,en"
	]

  	Flavour = "university"
	Style = "modern"

	# !Important: Theme colors can be selected in static/less/vitality.less
	
	Name = "Lebenslauf und Profil"
	Description = "Michael Schmidt"
	Favicon = "favicon.ico"
	Author = "Lafisrap (Michael Schmidt)"

	Fonts = [
		"Rajdhani:400,500,700",
		"IM+Fell+English+SC&amp;subset=latin-ext",
		"Josefin+Sans:300,300i,400,400i,700,700i",
	]
